version: '3.1'
services:
  shiny:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3838:3838"
    volumes:
      - log:/var/log/shiny-server
      - ./App:/srv/shiny-server

volumes:
  log:
